server:
  port: 8080

spring:
  application:
    name: springboot-dubbo-consumer

dubbo:
  scan:
    base-packages: com.javashitang.consumer.controller
  registry:
    protocol: zookeeper
    address: myhost:2181
  consumer:
    # check 为 false 的话那么 consumer 启动时不会去检查 producer 启动与否
    check: false
    timeout: 60000