server:
  port: 8081

spring:
  application:
    name: springboot-dubbo-producer

dubbo:
  registry:
    # 注册中心地址及协议
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
    threads: 3