server:
  port: 8081

spring:
  application:
    name: springboot-dubbo-producer

dubbo:
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.javashitang.producer.service
  protocol:
    # 协议名称和端口
    port: 20881
    name: dubbo
  registry:
    # 注册中心地址及协议
    address: 127.0.0.1:2181
    # 可选的协议有dubbo，zookeeper，redis，consul 等
    protocol: zookeeper
  # 假如使用新的 dubbo-admin 的话记得添加元数据配置，这样可以在 dubbo-admin 用来调试 provider 的服务
  metadata-report:
    address: zookeeper://127.0.0.1:2181